### ISSUE TITLE
data.txt

### ISSUE THREAD

**Issue by SilverHawk2020** [yn-sun/e2epp#1]
Could you please further clarify the encoding of the CNNs in the data.txt file? I've tried the encoding according to what's written in the paper, but I get totally different output, the ordering of the encoded elements doesn't seem to be the same.
So, either providing a complete example of 1 encoded  CNN; i.e. Clarifying the elements of one row of the provided file", or providing the encoding function would be really helpful.

**Comment by yn-sun** [comment]
I have the script for the encoding, however, I am not sure whether it is proper to send them to you. Please let me know you email address, I could send you some example data.

**Comment by SilverHawk2020** [comment]
Thank you Prof. Sun for your efforts, this is my email address:
noha.wahdan2020@gmail.com
Some emaple data would be highly appreciated.
